"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { z } from "zod";
const versionSchema = z.object({ id: z.string(), version_label: z.string(), status: z.string(), region: z.string(), license_type: z.string(), item_count: z.number(), error_count: z.number(), embedding_model: z.string(), collection_name: z.string().nullable() });
const issueSchema = z.object({ id: z.string(), external_id: z.string().nullable(), row_number: z.number().nullable(), issue_type: z.string(), severity: z.string(), safe_message: z.string(), status: z.string() });
export function KnowledgeDetail({ id }: { id: string }) {
  const router = useRouter();
  const [version, setVersion] = useState<z.infer<typeof versionSchema> | null>(null); const [issues, setIssues] = useState<z.infer<typeof issueSchema>[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([fetch(`/api/staff-backend/staff/knowledge/versions/${id}`).then(r => r.json()), fetch(`/api/staff-backend/staff/knowledge/versions/${id}/issues`).then(r => r.json())]).then(([a,b]) => { setVersion(versionSchema.parse(a)); setIssues(z.object({ items: z.array(issueSchema) }).parse(b).items); }).catch(reason => setError(reason instanceof Error ? reason.message : "加载失败")); }, [id]);
  async function action(name: "rebuild-index" | "run-evaluation" | "activate" | "rollback") { setBusy(true); setError(""); try { const response = await fetch(`/api/staff-backend/staff/knowledge/versions/${id}/${name}`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() } }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "操作失败"); if (name === "run-evaluation") router.push(`/staff/evaluations/${body.id}`); else setVersion(versionSchema.parse(body)); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } }
  if (!version) return <div className="card status">{error || "正在加载题库版本…"}</div>;
  return <><Link className="backLink" href="/staff/knowledge">← 返回题库版本</Link><section className="detailHeader"><div><span className="statusPill">{version.status}</span><h1>{version.version_label}</h1><p className="reason">{version.region} · {version.license_type} · {version.embedding_model}</p></div><div className="actions">{["READY", "ACTIVE"].includes(version.status) && <button className="button secondaryButton" disabled={busy} onClick={() => action("rebuild-index")}>重建索引</button>}{["READY", "ACTIVE", "RETIRED"].includes(version.status) && <button className="button secondaryButton" disabled={busy || !version.collection_name} onClick={() => action("run-evaluation")}>运行离线评测</button>}{version.status === "READY" && version.error_count === 0 && <button className="button primary" disabled={busy || !version.collection_name} onClick={() => action("activate")}>设为生效版本</button>}{version.status === "RETIRED" && <button className="button primary" disabled={busy} onClick={() => action("rollback")}>回退到此版本</button>}</div></section>{error && <div className="card error">{error}</div>}<section className="card"><h2>机器校验</h2><p>{version.item_count} 道有效题，{version.error_count} 个异常。</p>{issues.length === 0 ? <p className="reason">没有发现阻断异常。</p> : <div className="issueList">{issues.map(issue => <article className="issueRow" key={issue.id}><span className="riskTag">{issue.severity} · {issue.issue_type}</span><strong>{issue.external_id || `第 ${issue.row_number} 行`}</strong><p>{issue.safe_message}</p></article>)}</div>}</section><section className="card"><h2>向量索引</h2><p className="reason">{version.collection_name || "尚未建立。构建完成后才能评测该版本。"}</p></section><section className="card"><h2>上线门禁</h2><p className="reason">激活前必须完成离线评测，P0 错误为 0 且标准答案正确率为 100%。</p></section></>;
}
