"use client";
/* eslint-disable @next/next/no-img-element -- authenticated private assets are not compatible with the public image optimizer. */
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ticketSchema, type Ticket } from "@/lib/schemas/domain";
const key = () => crypto.randomUUID();
export function StaffTicketDetail({ id }: { id: string }) {
  const router = useRouter(); const [ticket, setTicket] = useState<Ticket | null>(null); const [reply, setReply] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setError(""); const response = await fetch(`/api/staff-backend/staff/review-tickets/${id}`, { cache: "no-store" }); if (response.status === 401) { router.replace("/staff/enter"); return; } const body = await response.json(); if (!response.ok) { setError(body.error?.message ?? "加载失败"); return; } setTicket(ticketSchema.parse(body)); }, [id, router]);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- initial ticket data is loaded from the backend here.
  useEffect(() => { void load(); }, [load]);
  async function action(path: "claim" | "reply", body: object) { setBusy(true); setError(""); try { const response = await fetch(`/api/staff-backend/staff/review-tickets/${id}/${path}`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": key() }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message ?? "操作失败"); setTicket(ticketSchema.parse(data)); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!ticket || reply.trim().length < 2) return; await action("reply", { version: ticket.version, content: reply }); setReply(""); }
  if (!ticket) return <div className="card status">{error || "正在加载工单…"}</div>;
  return <><button className="backLink" onClick={() => router.push("/staff/tickets")}>← 返回工单队列</button><section className="detailHeader"><div><span className={`statusPill status-${ticket.status.toLowerCase()}`}>{ticket.label}</span><h1>工单详情</h1></div>{["QUEUED", "SUBMITTED"].includes(ticket.status) && <button className="button primary" disabled={busy} onClick={() => action("claim", { version: ticket.version })}>认领并开始处理</button>}</section>{error && <div className="card error" role="alert">{error}</div>}<div className="detailGrid"><div><section className="card"><span className="mode">学员问题</span><p className="questionText">{ticket.question?.text}</p>{ticket.ocr && <img className="ocrPreview" src={ticket.ocr.preview_url} alt="学员上传题目"/>}</section><section className="card"><h2>AI 回答与依据</h2>{ticket.answer ? <><div className="direct">{ticket.answer.direct_answer}</div><p>{ticket.answer.short_reason}</p><details><summary>详细解释</summary><p className="detailText">{ticket.answer.detail}</p></details>{ticket.answer.evidence.map((item, i) => <div className="evidence" key={i}><strong>{item.title}</strong><br/>{item.excerpt}</div>)}</> : <p className="reason">该问题尚无 AI 回答，需直接判断。</p>}</section></div><aside><section className="card"><h2>风险与处理</h2><div className="riskList">{ticket.risk_codes.map(code => <span className="riskTag" key={code}>{code}</span>)}</div><p className="privacy">{ticket.sla}</p></section><section className="card"><h2>公开回复</h2>{ticket.messages.map(message => <div className="message" key={message.id}><strong>校长回复</strong><p>{message.content}</p></div>)}{ticket.status === "PROCESSING" && <form onSubmit={submit}><textarea className="input" value={reply} onChange={e => setReply(e.target.value)} placeholder="给学员明确、可执行的解释…" maxLength={4000}/><div className="actions"><button className="button primary" disabled={busy || reply.trim().length < 2}>发送给学员</button></div></form>}{ticket.status === "REPLIED" && <p className="reason">已回复，等待学员确认解决。</p>}{ticket.status === "CLOSED" && <p className="reason">学员已确认问题解决。</p>}</section></aside></div></>;
}
