"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, RotateCcw } from "lucide-react";
import { z } from "zod";

const questionSchema=z.object({id:z.string(),external_id:z.string(),stem:z.string(),options:z.array(z.object({label:z.string(),text:z.string()})),standard_answer:z.string(),explanation:z.string()});
const responseSchema=z.object({knowledge_version:z.string().nullable(),items:z.array(questionSchema)});
export function PracticeWorkspace(){const [items,setItems]=useState<z.infer<typeof questionSchema>[]>([]);const [index,setIndex]=useState(0);const [selected,setSelected]=useState("");const [error,setError]=useState("");const [version,setVersion]=useState("");useEffect(()=>{fetch("/api/backend/practice/questions",{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error?.message??"加载失败");const parsed=responseSchema.parse(body);setItems(parsed.items);setVersion(parsed.knowledge_version??"")}).catch(e=>setError(e instanceof Error?e.message:"加载失败"))},[]);const current=items[index];function move(next:number){setIndex(next);setSelected("");window.scrollTo({top:0,behavior:"smooth"})}if(error)return <><Link className="backLink" href="/ask">← 返回答疑</Link><div className="card error">{error}</div></>;if(!current)return <><Link className="backLink" href="/ask">← 返回答疑</Link><section className="hero"><h1>开始刷题</h1><p>{items.length===0?"当前没有已激活的 C1 科目一题库。":"正在加载题库…"}</p></section></>;const answered=Boolean(selected);const correct=selected===current.standard_answer;return <><div className="practiceTop"><Link className="backLink" href="/ask">← 返回首页</Link><span>{index+1} / {items.length}</span></div><section className="hero"><h1>顺序练习</h1><p>{version&&`题库版本：${version} · `}选择答案后立即查看解析。</p></section><section className="card practiceCard"><span className="questionNumber">第 {index+1} 题</span><h2>{current.stem}</h2><div className="optionList">{current.options.map(option=>{const isSelected=selected===option.label;const isAnswer=answered&&option.label===current.standard_answer;return <button key={option.label} disabled={answered} className={`practiceOption ${isAnswer?"correct":isSelected?"wrong":""}`} onClick={()=>setSelected(option.label)}><span>{option.label}</span><strong>{option.text}</strong>{isAnswer&&<CheckCircle2 aria-hidden="true" size={20}/>}</button>})}</div>{answered&&<div className={correct?"practiceResult correctResult":"practiceResult wrongResult"}><strong>{correct?"回答正确":"回答错误"}</strong><p>正确答案：{current.standard_answer}</p><p>{current.explanation}</p></div>}</section><div className="practiceActions"><button className="button secondaryButton" disabled={index===0} onClick={()=>move(index-1)}><ArrowLeft size={18}/>上一题</button>{answered?<button className="button primary" onClick={()=>index<items.length-1?move(index+1):move(0)}>{index<items.length-1?<><span>下一题</span><ArrowRight size={18}/></>:<><RotateCcw size={18}/><span>重新开始</span></>}</button>:<span className="practiceHint">请先选择一个答案</span>}</div></>}
