"""initial schema

Revision ID: c89181af4122
Revises: 
Create Date: 2026-08-26 18:10:47.562910
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'c89181af4122'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('anonymous_id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('license_type', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('session_token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_anonymous_id'), 'students', ['anonymous_id'], unique=True)
    op.create_index(op.f('ix_students_session_token_hash'), 'students', ['session_token_hash'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_student_id'), 'conversations', ['student_id'], unique=False)
    op.create_table('invitation_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_codes_code_hash'), 'invitation_codes', ['code_hash'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_conversation_id'), 'questions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_questions_request_id'), 'questions', ['request_id'], unique=True)
    op.create_table('ai_traces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('workflow_version', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_traces_question_id'), 'ai_traces', ['question_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('direct_answer', sa.Text(), nullable=False),
    sa.Column('short_reason', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('common_mistake', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('review_tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('risk_codes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tickets_question_id'), 'review_tickets', ['question_id'], unique=False)
    op.create_index(op.f('ix_review_tickets_student_id'), 'review_tickets', ['student_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('answer_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_answer_id'), 'evidence', ['answer_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('answer_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_answer_id'), 'feedback', ['answer_id'], unique=False)
    op.create_index(op.f('ix_feedback_student_id'), 'feedback', ['student_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_student_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_answer_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_evidence_answer_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_review_tickets_student_id'), table_name='review_tickets')
    op.drop_index(op.f('ix_review_tickets_question_id'), table_name='review_tickets')
    op.drop_table('review_tickets')
    op.drop_table('answers')
    op.drop_index(op.f('ix_ai_traces_question_id'), table_name='ai_traces')
    op.drop_table('ai_traces')
    op.drop_index(op.f('ix_questions_request_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_conversation_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_invitation_codes_code_hash'), table_name='invitation_codes')
    op.drop_table('invitation_codes')
    op.drop_index(op.f('ix_conversations_student_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_students_session_token_hash'), table_name='students')
    op.drop_index(op.f('ix_students_anonymous_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###

